/* 
*   Speech.java generated by speechmod 
*/
package Modalities;

import scxmlgen.interfaces.IModality;


public enum Gestures implements IModality{

 
    // ----------------Complementary----------------
	 
    Delete("[GESTURES][Delete]", 10000),
    Archive("[GESTURES][Archive]", 10000),

    // ----------------Redundant----------------

    Help("[GESTURES][Help]", 1000000),
    Read("[GESTURES][Read]", 10000),

    // ----------------Single----------------
     
    Up("[GESTURES][Up]", 1000),
    Down("[GESTURES][Down]", 1000), 
    Select("[GESTURES][Select]", 1000), 
    ;

    
    private String event;
    private int timeout;


    Gestures(String m, int time) {
        event=m;
        timeout=time;
    }

    @Override
    public int getTimeOut() {
        return timeout;
    }

    @Override
    public String getEventName() {
        //return getModalityName()+"."+event;
        return event;
    }

    @Override
    public String getEvName() {
        return getModalityName().toLowerCase()+event.toLowerCase();
    }
    
}